In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("student-mat.csv", sep=";")

In [3]:
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]


In [4]:
df.isnull()

school    sex    age  address  famsize  Pstatus   Medu   Fedu   Mjob  \
0     False  False  False    False    False    False  False  False  False   
1     False  False  False    False    False    False  False  False  False   
2     False  False  False    False    False    False  False  False  False   
3     False  False  False    False    False    False  False  False  False   
4     False  False  False    False    False    False  False  False  False   
..      ...    ...    ...      ...      ...      ...    ...    ...    ...   
390   False  False  False    False    False    False  False  False  False   
391   False  False  False    False    False    False  False  False  False   
392   False  False  False    False    False    False  False  False  False   
393   False  False  False    False    False    False  False  False  False   
394   False  False  False    False    False    False  False  False  False   

      Fjob  ...  famrel  freetime  goout   Dalc   Walc  health  absences  \
0    False  ...   False     False  False  False  False   False     False   
1    False  ...   False     False  False  False  False   False     False   
2    False  ...   False     False  False  False  False   False     False   
3    False  ...   False     False  False  False  False   False     False   
4    False  ...   False     False  False  False  False   False     False   
..     ...  ...     ...       ...    ...    ...    ...     ...       ...   
390  False  ...   False     False  False  False  False   False     False   
391  False  ...   False     False  False  False  False   False     False   
392  False  ...   False     False  False  False  False   False     False   
393  False  ...   False     False  False  False  False   False     False   
394  False  ...   False     False  False  False  False   False     False   

        G1     G2     G3  
0    False  False  False  
1    False  False  False  
2    False  False  False  
3    False  False  False  
4    False  False  False  
..     ...    ...    ...  
390  False  False  False  
391  False  False  False  
392  False  False  False  
393  False  False  False  
394  False  False  False  

[395 rows x 33 columns]

In [5]:
df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [6]:
df = df.drop('school', axis=1)

In [7]:
df = df.drop('famsize', axis=1)

In [8]:
df = df.drop('Medu', axis=1)

In [9]:
df = df.drop('Fedu', axis=1)

In [10]:
df = df.drop('Mjob', axis=1)

In [11]:
df = df.drop('Fjob', axis=1)

In [12]:
df = df.drop('famrel', axis=1)

In [13]:
df = df.drop('Dalc', axis=1)

In [14]:
df = df.drop('Walc', axis=1)

In [16]:
df = df.drop('sex', axis=1)

In [17]:
df = df.drop('address', axis=1)

In [18]:
df = df.drop('reason', axis=1)

In [19]:
df = df.drop('guardian', axis=1)

In [20]:
df = df.drop('traveltime', axis=1)

In [23]:
df = df.drop('age', axis=1)

In [24]:
df = df.drop('schoolsup', axis=1)

In [25]:
df = df.drop('nursery', axis=1)

In [26]:
df = df.drop('famsup', axis=1)

In [27]:
df = df.drop('paid', axis=1)

In [28]:
df = df.drop('romantic', axis=1)

In [29]:
df = df.drop('Pstatus', axis=1)

In [31]:
df = df.drop('activities', axis=1)

In [32]:
df = df.drop('higher', axis=1)

In [33]:
df = df.drop('internet', axis=1)

In [34]:
df.head()

studytime  failures  freetime  goout  health  absences  G1  G2  G3
0          2         0         3      4       3         6   5   6   6
1          2         0         3      3       3         4   5   5   6
2          2         3         3      2       3        10   7   8  10
3          3         0         2      2       5         2  15  14  15
4          2         0         3      2       5         4   6  10  10

In [35]:
X= df.iloc[:, :-1].values
y= df.iloc[:, -1].values

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
print(X_train)

[[ 2  0  2 ...  2 12 13]
 [ 1  0  3 ...  0 13 14]
 [ 2  3  3 ...  0  8  7]
 ...
 [ 2  2  3 ... 15  9  9]
 [ 3  0  4 ...  0 13 15]
 [ 1  0  3 ...  4 10 13]]


In [39]:
print(y_train)

[12 14  0  9  8  7 14  0 12 15  0 13  9 11 10  0  8 10 18 19 14 12 13  6
 10 10  8 10  8  9  0  7  5 11  5 10 18  8  8 16 10 12  8 11 16 11 12 13
  0  0  8 12 10 13  0 18 15  0 11 18 12 10 13 10 16 10 11 15 11 11 14  0
  9  8  6 11 11 13 10 14 10  8  7  6 11 17  6 16 13 15 13 16 10  9  8 12
 15  0 13  6  8 10 12 11  8 12  0 12  6  0 10  0 15 10 14  8  6 11 13  8
 18 11 12 10 11 13 13 11 17  9 13 15  9 10 10 11  7  8  0 12 10 10  0 10
 11 16  9 11 11 15 14 14 12 17 13 11  9 11 10 11 15 16 18  9  0 11  0 12
 19  9 10 15 13  8  0 11 15 12 14  6 11  0 11 13 10  0 10 13 12 14 12  9
 12  8  7 12 10 10 13  8  5 15  0  8 16 14 15 11 20 16 11 16 13 15 15 14
 18 14  0 15 12  9  0  0 19 10 11 16 13 11 12 11  4 10  0 13 13 14 11 14
 10 10 13 18  0 10  7 11  8 13 10  0 11 11  6  7 12  9 15  9 18 10 10  0
 12 11 11 10 14 10  9  8  0 18 15 11 12 13 13  9 10  7 15 14  9 14 10 10
  8 15 11  0  9  9 18  0 11 12 10  0 14 16  8 11 14  8 10 15  9 15  9 10
  8  9 15 14]


In [40]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [41]:
print(X_train)

[[ 2  0  2 ...  2 12 13]
 [ 1  0  3 ...  0 13 14]
 [ 2  3  3 ...  0  8  7]
 ...
 [ 2  2  3 ... 15  9  9]
 [ 3  0  4 ...  0 13 15]
 [ 1  0  3 ...  4 10 13]]


In [42]:
print(X_test)

[[ 1  3  5  1  3  2  8  8]
 [ 1  0  3  3  3  3 14 12]
 [ 2  1  3  3  5  8  3  5]
 [ 2  0  3  4  2  8  8  9]
 [ 2  2  5  4  4 11  9  9]
 [ 2  0  3  3  4  0 12 13]
 [ 2  0  3  3  5  2 19 18]
 [ 2  0  4  2  5 18  9  7]
 [ 2  0  3  3  1  0  8  8]
 [ 2  0  4  3  2  2 11 13]
 [ 2  0  5  1  5  0 14 15]
 [ 3  0  4  2  4  6  7  7]
 [ 3  0  4  3  5  1 12 14]
 [ 1  0  4  1  5  0 11 12]
 [ 2  0  2  4  4  8 15 14]
 [ 2  0  4  4  1  2 11  8]
 [ 2  0  4  4  5  0  8  7]
 [ 2  0  4  3  3  2 11 11]
 [ 3  0  3  3  2  0 16 15]
 [ 4  0  4  4  4  0 10  9]
 [ 1  0  4  4  2  4 14 14]
 [ 1  0  4  5  2  3 14 16]
 [ 2  0  2  3  3  0 14 15]
 [ 2  0  3  4  3  6  5  6]
 [ 4  0  2  2  3  0  7  9]
 [ 1  0  5  2  3 10 18 19]
 [ 4  0  2  3  3  0 11 11]
 [ 2  0  3  2  2  0  8 10]
 [ 3  0  4  3  4  0 16 17]
 [ 4  0  4  3  1  8 11 11]
 [ 1  1  3  4  4 38  8  9]
 [ 3  0  3  2  4  2  8  8]
 [ 3  0  2  2  3  0 15 15]
 [ 2  0  3  3  5  4 12 13]
 [ 3  0  3  3  4  0  7  7]
 [ 1  1  4  3  3 14  6  5]
 [ 1  2  3  2  5  0  4  0]
 

In [43]:
y_pred = regressor.predict(X_test)

In [44]:
print(y_pred)

[ 5.62520265 12.0946996   3.48409641  8.50720968  8.0773331  12.73304351
 18.82814016  7.09598126  6.96149931 12.55270934 14.89624416  6.20359981
 13.86195427 11.49628969 14.5571547   7.65189662  6.51073082 10.65697123
 15.05597671  8.60264145 14.22424865 16.30864607 14.85537092  5.1229572
  7.7135172  19.83174377 10.39314964  8.88844916 17.26293426 10.64601443
  9.45788946  7.12026656 14.81099463 12.98244218  6.05151206  4.06148081
 -2.2434846  15.04914419 11.80797364  7.47365867  4.58447925 10.19095623
 14.12362758  7.57842149 15.25069752  9.36002054 12.28887975 14.57664981
 12.64287734 15.64811511 12.9174269  14.5899421  10.32960489  8.25289362
  4.43344078 13.26400087  9.8404614   6.13693486 15.11617358 16.20206174
 12.89957488  8.52335842  6.43097612  4.27587462  5.00909158 17.24787126
  7.99373222  9.45570755  9.89773537 15.53305116  7.44080038  9.28205287
 13.39178665 19.89848194 10.47046055  5.78719835  8.67215269 14.07466206
  3.68653227]


In [45]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 5.63 10.  ]
 [12.09 12.  ]
 [ 3.48  5.  ]
 [ 8.51 10.  ]
 [ 8.08  9.  ]
 [12.73 13.  ]
 [18.83 18.  ]
 [ 7.1   6.  ]
 [ 6.96  0.  ]
 [12.55 14.  ]
 [14.9  15.  ]
 [ 6.2   7.  ]
 [13.86 15.  ]
 [11.5  10.  ]
 [14.56 14.  ]
 [ 7.65  8.  ]
 [ 6.51  8.  ]
 [10.66 11.  ]
 [15.06 15.  ]
 [ 8.6   0.  ]
 [14.22 14.  ]
 [16.31 16.  ]
 [14.86 16.  ]
 [ 5.12  6.  ]
 [ 7.71  0.  ]
 [19.83 19.  ]
 [10.39 11.  ]
 [ 8.89 12.  ]
 [17.26 17.  ]
 [10.65 10.  ]
 [ 9.46  8.  ]
 [ 7.12 10.  ]
 [14.81 15.  ]
 [12.98 13.  ]
 [ 6.05  8.  ]
 [ 4.06  5.  ]
 [-2.24  0.  ]
 [15.05 15.  ]
 [11.81 14.  ]
 [ 7.47  8.  ]
 [ 4.58  5.  ]
 [10.19 11.  ]
 [14.12 14.  ]
 [ 7.58  9.  ]
 [15.25 15.  ]
 [ 9.36 10.  ]
 [12.29 11.  ]
 [14.58 13.  ]
 [12.64 13.  ]
 [15.65 16.  ]
 [12.92 13.  ]
 [14.59 15.  ]
 [10.33 12.  ]
 [ 8.25 10.  ]
 [ 4.43  6.  ]
 [13.26 12.  ]
 [ 9.84 11.  ]
 [ 6.14  0.  ]
 [15.12 16.  ]
 [16.2  17.  ]
 [12.9  14.  ]
 [ 8.52 10.  ]
 [ 6.43 10.  ]
 [ 4.28  6.  ]
 [ 5.01  9.  ]
 [17.25 17.  ]
 [ 7.99  8

In [46]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_pred, y_test)
print("Mean Squared Error (MSE):", mse)


Mean Squared Error (MSE): 4.581777109481437
